import { useEffect, useRef, useState } from "react";
import type { LongEpisodeVideoProgress, LongEpisodeVideoReview, LongEpisodeVideoPreview, SceneNumber } from "@ai-animation-studio/shared";

import { approveLongEpisodeVideoReview, getLongEpisodeVideoPreview, getLongEpisodeVideoProgress, getLongEpisodeVideoReview, regenerateLongEpisodeVideo, restartLongEpisodeVideoGeneration, startLongEpisodeVideoGeneration, stopLongEpisodeVideoGeneration, toLongProjectDisplayError } from "../api/longProjectsApi.js";

interface Props { projectId: string; episodeNumber: number; onBack: () => void; onOpenMerge: (projectId: string, episodeNumber: number) => void; }
type DisplayError = { code: string; message: string };
const SCENES = [1, 2, 3, 4, 5, 6] as const satisfies readonly SceneNumber[];
const LIMIT = 1000;

export function LongEpisodeVideoWorkflowScreen({ projectId, episodeNumber, onBack, onOpenMerge }: Props) {
  const [preview, setPreview] = useState<{ confirmationId: string; scenes: LongEpisodeVideoPreview[]; estimatedCostUsd: number } | null>(null);
  const [prompts, setPrompts] = useState<Partial<Record<SceneNumber, string>>>({});
  const [job, setJob] = useState<LongEpisodeVideoProgress | null>(null);
  const [reviews, setReviews] = useState<LongEpisodeVideoReview[] | null>(null);
  const [confirmStart, setConfirmStart] = useState(false); const [regenerate, setRegenerate] = useState<SceneNumber | null>(null);
  const [busy, setBusy] = useState(false); const [error, setError] = useState<DisplayError | null>(null);
  const busyRef = useRef(false);
  const loadPreview = async () => { setError(null); try { const response = await getLongEpisodeVideoPreview(projectId, episodeNumber); setPreview(response); setPrompts(Object.fromEntries(response.scenes.map((scene) => [scene.sceneNumber, scene.prompt]))); } catch (caught) { setError(toLongProjectDisplayError(caught)); } };
  useEffect(() => { void loadPreview(); }, [projectId, episodeNumber]);
  const loadProgress = async () => { if (!job) return; try { const next = await getLongEpisodeVideoProgress(projectId, episodeNumber, job.jobId); setJob(next); if (next.status === "succeeded") { const review = await getLongEpisodeVideoReview(projectId, episodeNumber, next.jobId); setReviews(review.reviews); } } catch (caught) { setError(toLongProjectDisplayError(caught)); } };
  useEffect(() => { if (!job || (job.status !== "created" && job.status !== "running")) return; const timer = setTimeout(() => void loadProgress(), 400); return () => clearTimeout(timer); }, [job]);
  const valid = preview !== null && preview.scenes.every((scene) => { const prompt = prompts[scene.sceneNumber] ?? ""; return prompt.trim().length > 0 && prompt.length <= LIMIT; });
  async function start(): Promise<void> { if (!preview || !valid || busyRef.current) return; busyRef.current = true; setBusy(true); setError(null); try { const response = await startLongEpisodeVideoGeneration(projectId, episodeNumber, { confirmationId: preview.confirmationId, userRequestId: crypto.randomUUID(), approved: true, prompts: preview.scenes.map((scene) => ({ sceneNumber: scene.sceneNumber, prompt: prompts[scene.sceneNumber] ?? "" })) }); setJob({ jobId: response.jobId, status: "created", completedSceneNumbers: [], failedSceneNumbers: [], episode: response.episode }); setConfirmStart(false); } catch (caught) { setError(toLongProjectDisplayError(caught)); } finally { busyRef.current = false; setBusy(false); } }
  async function action(fn: () => Promise<LongEpisodeVideoProgress>): Promise<void> { if (busyRef.current) return; busyRef.current = true; setBusy(true); setError(null); try { setJob(await fn()); } catch (caught) { setError(toLongProjectDisplayError(caught)); } finally { busyRef.current = false; setBusy(false); } }
  async function approve(sceneNumber: SceneNumber): Promise<void> { if (!job) return; try { const response = await approveLongEpisodeVideoReview(projectId, episodeNumber, job.jobId, sceneNumber); setJob((current) => current ? { ...current, episode: response.episode } : current); setReviews(response.reviews); } catch (caught) { setError(toLongProjectDisplayError(caught)); } }
  return <section className="mt-8 space-y-4"><button type="button" onClick={onBack}>Episode images</button><h2 className="text-xl font-semibold">Episode {episodeNumber} video workflow</h2><p data-testid="episode-video-local-notice" className="text-sm text-amber-300">Local fake video workflow only. No Runway or provider request is sent.</p>
    {!preview && !error && <p>Loading local video preview...</p>}{preview && !job && <><p data-testid="episode-video-summary">Sequential · ${preview.estimatedCostUsd.toFixed(2)}</p><ol>{preview.scenes.map((scene) => <li key={scene.sceneNumber}><label>Scene {scene.sceneNumber} prompt<textarea data-testid={`episode-video-prompt-${scene.sceneNumber}`} value={prompts[scene.sceneNumber] ?? ""} disabled={confirmStart || busy} onChange={(event) => setPrompts((current) => ({ ...current, [scene.sceneNumber]: event.target.value }))} /></label><span>{(prompts[scene.sceneNumber] ?? "").length} / {LIMIT}</span></li>)}</ol><button type="button" data-testid="episode-video-open-confirm" disabled={!valid || confirmStart} onClick={() => setConfirmStart(true)}>Open local generation confirmation</button>{confirmStart && <div role="alertdialog" data-testid="episode-video-start-confirm"><p>Opening this confirmation made no request. Start the local fake sequential video job?</p><button type="button" disabled={busy} onClick={() => setConfirmStart(false)}>Cancel</button><button type="button" disabled={busy} onClick={() => void start()}>Start local fake videos</button></div>}</>}
    {job && <section data-testid="episode-video-progress"><p>Job: {job.status}</p><ol>{SCENES.map((scene) => <li key={scene} data-testid={`episode-video-progress-${scene}`}>{scene}: {job.completedSceneNumbers.includes(scene) ? "completed" : job.currentSceneNumber === scene ? "running" : job.failedSceneNumbers.includes(scene) ? "failed" : "pending"}</li>)}</ol>{(job.status === "created" || job.status === "running") && <button type="button" disabled={busy} onClick={() => void action(() => stopLongEpisodeVideoGeneration(projectId, episodeNumber, job.jobId))}>Stop</button>}{job.status === "interrupted" && <button type="button" disabled={busy} onClick={() => void action(() => restartLongEpisodeVideoGeneration(projectId, episodeNumber, job.jobId))}>Restart</button>}</section>}
    {job?.status === "failed" && <section data-testid="episode-video-failed-scenes"><p>Some scenes failed. You can retry a failed scene below.</p><ul>{job.failedSceneNumbers.map((scene) => <li key={scene} data-testid={`episode-video-failed-${scene}`}><span>Scene {scene}</span><button type="button" data-testid={`episode-video-failed-retry-${scene}`} disabled={busy || regenerate === scene} onClick={() => setRegenerate(scene)}>Retry scene</button>{regenerate === scene && <div role="alertdialog" data-testid={`episode-video-failed-retry-confirm-${scene}`}><p>Retry Scene {scene} with local fake video only?</p><button type="button" onClick={() => setRegenerate(null)}>Cancel</button><button type="button" disabled={busy} onClick={() => { setRegenerate(null); void action(() => regenerateLongEpisodeVideo(projectId, episodeNumber, job.jobId, scene)); }}>Retry scene</button></div>}</li>)}</ul></section>}
    {job?.status === "succeeded" && reviews && <section data-testid="episode-video-review"><h3>Video review</h3>{reviews.map((review) => <div key={review.sceneNumber} data-testid={`episode-video-review-${review.sceneNumber}`} data-status={review.status}><p>Scene {review.sceneNumber}: {review.status}</p><button type="button" disabled={review.status === "approved"} onClick={() => void approve(review.sceneNumber)}>{review.status === "approved" ? "Approved" : "Approve"}</button><button type="button" onClick={() => setRegenerate(review.sceneNumber)}>Regenerate</button>{regenerate === review.sceneNumber && <div role="alertdialog" data-testid={`episode-video-regenerate-confirm-${review.sceneNumber}`}><p>Regenerate Scene {review.sceneNumber} with local fake video only?</p><button type="button" onClick={() => setRegenerate(null)}>Cancel</button><button type="button" disabled={busy} onClick={() => { const scene = review.sceneNumber; setRegenerate(null); void action(() => regenerateLongEpisodeVideo(projectId, episodeNumber, job.jobId, scene)); }}>Regenerate scene</button></div>}</div>)}</section>}
    {job?.episode.status === "videos_approved" && <div data-testid="episode-videos-approved"><p>All six Episode videos are approved.</p><button type="button" data-testid="open-episode-video-merge" onClick={() => onOpenMerge(projectId, episodeNumber)}>Create final Episode video</button></div>}{error && <p role="alert" data-error-code={error.code}>{error.message}</p>}</section>;
}
