import { useEffect, useRef, useState } from "react";
import type { FormEvent } from "react";
import { isSha256Hex, sceneNumbersFor } from "@ai-animation-studio/shared";
import type {
  Asset,
  AssetMappingSceneScope,
  AssetMappingStatus,
  AssetType,
  ProjectAssetMapping,
  ProjectAssetMappingReview,
  SceneNumber,
  UpdateProjectAssetMappingDecision,
} from "@ai-animation-studio/shared";
import { getAsset, listAssets, toAssetDisplayError } from "../api/assetsApi.js";
import { type MappingApi, toMappingDisplayError } from "../api/mappingsApi.js";
import { formatDateTime } from "../utils/formatDateTime.js";
import { Spinner } from "./Spinner.js";

interface Props {
  /**
   * Who owns these mappings, as the set of calls that reach them — never an id (D-026). A short project and a Long
   * Episode run the same review flow over the same shapes, so this screen is written once and told where to
   * send its requests. See MappingApi's own doc comment for why an id would not do.
   */
  api: MappingApi;
  onBack: () => void;
  /** The next pipeline step (장면 이미지). Optional so the screen still renders standalone in tests. */
  onOpenImageGeneration?: () => void;
}

type DisplayError = { code: string; message: string; details?: Record<string, unknown> };

const STATUS_LABELS: Record<AssetMappingStatus, string> = {
  confirmed: "확인됨", suggested: "제안됨", ambiguous: "모호함",
  unmatched: "매칭 안 됨", excluded: "제외됨", invalid: "유효하지 않음",
};
const STATUS_TEXT_TONE: Record<AssetMappingStatus, string> = {
  confirmed: "text-emerald-300", suggested: "text-violet-300", ambiguous: "text-amber-300",
  unmatched: "text-slate-400", excluded: "text-rose-300", invalid: "text-rose-300",
};
// The Asset Library's own words, not a second set translated here — see docs/06_DECISIONS.md D-028.
const TYPE_LABELS: Record<AssetType, string> = {
  character: "캐릭터", style: "스타일", background: "배경", object: "소품", general_reference: "일반 참고",
};
/** Assets the user put into the Library themselves. Everything else was generated by some project run. */
const MANUAL_SOURCE_PROJECT_ID = "_asset_library_manual";

const outlineButton =
  "rounded-full border border-white/10 px-3 py-1.5 text-xs text-slate-300 hover:bg-white/5 disabled:opacity-50 disabled:hover:bg-transparent";
const selectClassName =
  "mt-1 rounded-lg border border-white/10 bg-slate-900/70 px-2.5 py-1.5 text-sm text-slate-100 focus:border-violet-400/50 focus:outline-none focus:ring-2 focus:ring-violet-500/30";

function scopeIncludesScene(scope: AssetMappingSceneScope, sceneNumber: SceneNumber): boolean {
  if (scope.kind === "all") return true;
  if (scope.kind === "scene") return scope.sceneNumber === sceneNumber;
  if (scope.kind === "range") return scope.startScene <= sceneNumber && sceneNumber <= scope.endScene;
  return scope.sceneNumbers.includes(sceneNumber);
}

function scopeLabel(scope: AssetMappingSceneScope): string {
  if (scope.kind === "all") return "전체 장면";
  if (scope.kind === "scene") return `씬 ${scope.sceneNumber}`;
  if (scope.kind === "range") return `씬 ${scope.startScene}~${scope.endScene}`;
  return `씬 ${scope.sceneNumbers.join(", ")}`;
}

function errorDetailLabel(details: Record<string, unknown> | undefined): string | null {
  if (!details) return null;
  if (Array.isArray(details.missingSceneNumbers) && details.missingSceneNumbers.length > 0) {
    return `이미지가 안 붙은 장면: ${details.missingSceneNumbers.join(", ")}번`;
  }
  if (Array.isArray(details.mappingIds) && details.mappingIds.length > 0) {
    return `아직 확인 안 한 연결 ${details.mappingIds.length}개`;
  }
  return null;
}

/**
 * The backend answers all three blocking situations with one code, so the screen — which knows the mapping
 * list — says which one it is. Without this, a project with nothing connected got told that "확인이 필요한
 * Mapping이 남아 있습니다" while the list right below it said there were none.
 */
/**
 * When the mapping file cannot be read, this screen is a dead end until someone touches that file, and what it
 * owes the person is the way out — not a red line they can only press again. The way out here is a warning,
 * not an instruction: a missing asset_mappings.json reads as "연결 없음", so deleting it to clear the error
 * throws away every link the person made by hand, with nothing that puts them back.
 *
 * There was a matching block for the review file, saying the opposite (that one IS safe to delete). It is gone:
 * ASSET_MAPPING_REVIEW_MALFORMED has had no producer since eef4a38, and ASSET_MAPPING_REVIEW_INVALID is raised
 * on the way *out* — the server's own record failing its own invariant — which deleting the file does not fix.
 * Advice for a code that cannot arrive is the same failure this screen keeps being fixed for, one level up:
 * the screen asserting something it never checked, and telling the next reader that a dead path is alive.
 */
const MAPPING_FILE_UNREADABLE = new Set(["ASSET_MAPPING_JSON_MALFORMED", "ASSET_MAPPING_DATA_INVALID"]);
const fileName = "rounded bg-white/5 px-1 py-0.5 font-mono text-[11px] text-slate-300";
const recoveryNote = "mt-2 text-xs leading-relaxed text-slate-400";

function blockedReason(mappings: ProjectAssetMapping[] | null, details: Record<string, unknown> | undefined): string | null {
  if (Array.isArray(details?.missingSceneNumbers) && details!.missingSceneNumbers.length > 0) {
    return "이미지가 하나도 안 붙은 장면이 있습니다. 그 장면에 이미지를 연결하거나, 아래 \"특별한 경우\"에서 이미지 없이 진행하도록 켜 주세요.";
  }
  if (mappings && mappings.length === 0) {
    return "참고 이미지를 하나도 연결하지 않았습니다. 글만으로 그림을 만들려면 아래 \"참고 이미지 없이 진행하기\"를 눌러 주세요.";
  }
  // Null is "the list was not read", not "there is something left to confirm in it". The sentence below points
  // at a list that is not on screen, and names a cause the screen has no way to know — the server refused for
  // some reason, and this one was being printed for every one of them.
  if (mappings === null) {
    return "연결 목록을 읽지 못해서, 무엇이 남았는지 확인할 수 없습니다. 위의 새로고침을 눌러 다시 시도해 주세요.";
  }
  return "아직 확인하지 않은 연결이 남아 있습니다. 아래 목록에서 확인 또는 제외를 눌러 주세요.";
}

export function MappingReviewScreen({ api, onBack, onOpenImageGeneration }: Props) {
  const [mappings, setMappings] = useState<ProjectAssetMapping[] | null>(null);
  const [mappingsError, setMappingsError] = useState<DisplayError | null>(null);
  const [mappingsLoading, setMappingsLoading] = useState(true);
  const [review, setReview] = useState<ProjectAssetMappingReview | null>(null);
  /**
   * How many scenes this owner has, straight from the review response — null until it has been read.
   *
   * The scene pickers used to be filled from the full supported range (2-12) because the screen had no way to
   * know the real number. On a four-scene project that offered scenes five and six, and picking one produced
   * INVALID_REQUEST from the server: the app offered a choice it would not accept. It cannot be read off
   * `review.reviewedScenes` either — that starts empty and records what a reviewer marked, not what exists.
   *
   * Null is kept distinct from a number rather than defaulting to anything: a default here would be a guess
   * about the very thing that was wrong, and a wrong guess looks identical to a right one on screen. While it
   * is null the scene choices are withheld instead (see sceneNumbers below).
   */
  const [sceneCount, setSceneCount] = useState<number | null>(null);
  const [reviewError, setReviewError] = useState<DisplayError | null>(null);
  const [reviewLoading, setReviewLoading] = useState(true);
  const [assets, setAssets] = useState<Record<string, Asset>>({});
  const [assetErrors, setAssetErrors] = useState<Record<string, DisplayError>>({});

  const [statusFilter, setStatusFilter] = useState<AssetMappingStatus | "">("");
  /**
   * "제외" means "do not use this one", and there is no delete — the row stayed in the list looking exactly
   * as present as the ones in use, which reads as if the exclusion did not take. Out of the way by default,
   * still reachable, because an excluded row is the record of a decision and sometimes gets undone.
   */
  const [showExcluded, setShowExcluded] = useState(false);
  const [typeFilter, setTypeFilter] = useState<AssetType | "">("");
  const [sceneFilter, setSceneFilter] = useState<SceneNumber | "">("");

  const [textOnlyConfirmed, setTextOnlyConfirmed] = useState(false);
  const [legacyConfirmed, setLegacyConfirmed] = useState(false);
  const [beginPending, setBeginPending] = useState(false);
  const [approvePending, setApprovePending] = useState(false);
  const [reviewMutationError, setReviewMutationError] = useState<DisplayError | null>(null);

  const [decisionPendingIds, setDecisionPendingIds] = useState<Set<string>>(new Set());
  const [snapshotPendingIds, setSnapshotPendingIds] = useState<Set<string>>(new Set());
  const [decisionErrors, setDecisionErrors] = useState<Record<string, DisplayError>>({});
  const [snapshotErrors, setSnapshotErrors] = useState<Record<string, DisplayError>>({});

  /**
   * The "connect a reference image" form. This screen could review connections but never make one, and
   * nothing else in the app made them either — so `collectReferenceImages` always came up empty and every
   * scene image was drawn from prompt text alone, with no character or background picture attached.
   */
  const [addQuery, setAddQuery] = useState("");
  const [addResults, setAddResults] = useState<Asset[] | null>(null);
  const [addSearchLoading, setAddSearchLoading] = useState(false);
  const [addSearchError, setAddSearchError] = useState<DisplayError | null>(null);
  const [addRole, setAddRole] = useState("character");
  const [addScope, setAddScope] = useState<"all" | "scene">("all");
  const [addScene, setAddScene] = useState<SceneNumber>(1 as SceneNumber);
  const [addPendingIds, setAddPendingIds] = useState<Set<string>>(new Set());
  const [addError, setAddError] = useState<DisplayError | null>(null);
  const addBusy = useRef<Set<string>>(new Set());

  const loadRequest = useRef(0);
  const decisionBusy = useRef<Set<string>>(new Set());
  const snapshotBusy = useRef<Set<string>>(new Set());
  const beginBusy = useRef(false);
  const approveBusy = useRef(false);

  async function loadAssetDetails(list: ProjectAssetMapping[], requestId: number) {
    const uniqueIds = [...new Set(list.map((item) => item.assetId))];
    const results = await Promise.allSettled(uniqueIds.map((assetId) => getAsset(assetId)));
    if (requestId !== loadRequest.current) return;
    const nextAssets: Record<string, Asset> = {};
    const nextErrors: Record<string, DisplayError> = {};
    uniqueIds.forEach((assetId, index) => {
      const outcome = results[index]!;
      if (outcome.status === "fulfilled") nextAssets[assetId] = outcome.value.asset;
      else nextErrors[assetId] = toAssetDisplayError(outcome.reason);
    });
    setAssets(nextAssets);
    setAssetErrors(nextErrors);
  }

  async function load() {
    const requestId = ++loadRequest.current;
    setMappingsLoading(true);
    setReviewLoading(true);
    const [mappingsResult, reviewResult] = await Promise.allSettled([
      api.list(),
      api.getReview(),
    ]);
    if (requestId !== loadRequest.current) return;
    if (mappingsResult.status === "fulfilled") {
      setMappings(mappingsResult.value.mappings);
      setMappingsError(null);
      void loadAssetDetails(mappingsResult.value.mappings, requestId);
    } else {
      setMappingsError(toMappingDisplayError(mappingsResult.reason));
    }
    if (reviewResult.status === "fulfilled") {
      setReview(reviewResult.value.review);
      setSceneCount(reviewResult.value.sceneCount);
      setReviewError(null);
    } else {
      setReviewError(toMappingDisplayError(reviewResult.reason));
    }
    setMappingsLoading(false);
    setReviewLoading(false);
  }

  // api.id, not api: a caller that builds the adapter inline gets a new object every render, and depending
  // on object identity here would re-fetch forever.
  useEffect(() => { void load(); }, [api.id]);

  /**
   * The scenes this owner actually has, and nothing else. Empty while the review has not been read yet or
   * failed to load — the pickers below are disabled in that state rather than falling back to a range, so the
   * screen never offers a scene the server would reject.
   */
  const sceneNumbers: readonly SceneNumber[] = sceneCount === null ? [] : sceneNumbersFor(sceneCount);

  async function searchAssets(event: FormEvent): Promise<void> {
    event.preventDefault();
    setAddSearchLoading(true);
    setAddSearchError(null);
    try {
      const response = await listAssets({ query: addQuery.trim() || undefined });
      // Two exclusions, both about not offering something that cannot sensibly be a reference.
      //
      // Children of a Folder: a Folder mapping already resolves to whichever child is its representative, so
      // listing them separately shows the same picture twice under two names — and picking the child alone
      // loses the Folder's shared description.
      //
      // Anything the Library did not receive by hand (`sourceProjectId !== "_asset_library_manual"`) is a
      // picture some project GENERATED, including this project's own scene images, which the Library files
      // into an auto-made folder. Offering those as reference material invites feeding a project's output
      // back in as its own input — the user hit exactly that: a folder literally named "1 generated images"
      // sat in this list beside their character.
      setAddResults(response.assets.filter(
        (asset) => !asset.parentFolderId && asset.sourceProjectId === MANUAL_SOURCE_PROJECT_ID,
      ));
    } catch (caught) {
      setAddSearchError(toAssetDisplayError(caught));
    } finally {
      setAddSearchLoading(false);
    }
  }

  async function addMapping(asset: Asset): Promise<void> {
    if (addBusy.current.has(asset.assetId)) return;
    addBusy.current.add(asset.assetId);
    setAddPendingIds(new Set(addBusy.current));
    setAddError(null);
    try {
      const sceneScope: AssetMappingSceneScope = addScope === "scene"
        ? { kind: "scene", sceneNumber: addScene }
        : { kind: "all" };
      await api.create({ assetId: asset.assetId, usageRole: addRole, sceneScope });
      // Reload rather than splice the new row in: the created mapping needs its Asset details fetched, and
      // the review's own counters change too.
      await load();
    } catch (caught) {
      setAddError(toMappingDisplayError(caught));
    } finally {
      addBusy.current.delete(asset.assetId);
      setAddPendingIds(new Set(addBusy.current));
    }
  }

  /**
   * 🔴 `enabled: true` rides along with every 확인, and leaving it off cost Captain D a paid Episode.
   *
   * The server's two decisions are not mirror images (mappings.service.ts):
   *
   *   exclude → status = "excluded",  user_confirmed = false,  enabled = false
   *   confirm → status = "confirmed", user_confirmed = true                     ← enabled is never put back
   *
   * So exclude-then-confirm lands on `status: "confirmed"` with `enabled: false`. Every screen reads the
   * status and calls that row 연결됨 · 확인됨; the one thing that reads `enabled` is the code that decides
   * what the image model is actually shown (image-reference-selection.ts: `status === "confirmed" && enabled`),
   * and it skips the row in silence. Measured on 12/Episode04: both mappings sat at
   * `enabled: false, status: "confirmed"`, the screen said 연결됨, and nothing warned anyone.
   *
   * The round trip existed before this screen had a toggle — 제외 then 확인 on the row below did the same —
   * but the toggle put it one press away on the button people actually press, so this is the call site that
   * has to be safe. Sending `enabled` explicitly rather than waiting for the server to be fixed: the request
   * that says "use this one" should say so completely, and a screen that only half-restores a connection is
   * the defect whatever the server does with it.
   */
  async function decide(mappingId: string, decision: UpdateProjectAssetMappingDecision) {
    if (decisionBusy.current.has(mappingId)) return;
    decisionBusy.current.add(mappingId);
    setDecisionPendingIds(new Set(decisionBusy.current));
    try {
      const response = await api.update(mappingId, decision === "confirm" ? { decision, enabled: true } : { decision });
      setMappings((current) => (current ? current.map((item) => (item.mappingId === mappingId ? response.mapping : item)) : current));
      setReview(response.review);
      setDecisionErrors((current) => {
        if (!(mappingId in current)) return current;
        const next = { ...current };
        delete next[mappingId];
        return next;
      });
    } catch (caught) {
      setDecisionErrors((current) => ({ ...current, [mappingId]: toMappingDisplayError(caught) }));
    } finally {
      decisionBusy.current.delete(mappingId);
      setDecisionPendingIds(new Set(decisionBusy.current));
    }
  }

  async function createSnapshot(mappingId: string) {
    if (snapshotBusy.current.has(mappingId)) return;
    snapshotBusy.current.add(mappingId);
    setSnapshotPendingIds(new Set(snapshotBusy.current));
    try {
      const response = await api.snapshot(mappingId);
      setMappings((current) => (current ? current.map((item) => (item.mappingId === mappingId ? response.mapping : item)) : current));
      setSnapshotErrors((current) => {
        if (!(mappingId in current)) return current;
        const next = { ...current };
        delete next[mappingId];
        return next;
      });
    } catch (caught) {
      setSnapshotErrors((current) => ({ ...current, [mappingId]: toMappingDisplayError(caught) }));
    } finally {
      snapshotBusy.current.delete(mappingId);
      setSnapshotPendingIds(new Set(snapshotBusy.current));
    }
  }

  async function beginReview() {
    if (beginBusy.current) return;
    beginBusy.current = true;
    setBeginPending(true);
    setReviewMutationError(null);
    try {
      const response = await api.beginReview({
        scriptRevision: review?.scriptRevision ?? 0,
        textOnlyConfirmed,
        legacyConfirmed,
      });
      setReview(response.review);
    } catch (caught) {
      setReviewMutationError(toMappingDisplayError(caught));
    } finally {
      beginBusy.current = false;
      setBeginPending(false);
    }
  }

  /**
   * The whole "nothing to connect" path in one press. It used to require finding a checkbox called
   * "텍스트만 사용(매핑 없음) 확인", ticking it, pressing 검토 시작, then pressing 최종 승인 — four steps to say
   * "I have no reference images". The two requests still happen, just not as two things to figure out.
   */
  async function proceedWithoutImages() {
    if (beginBusy.current || approveBusy.current) return;
    beginBusy.current = true; setBeginPending(true); setReviewMutationError(null);
    try {
      const begun = await api.beginReview({
        scriptRevision: review?.scriptRevision ?? 0,
        textOnlyConfirmed: true,
        legacyConfirmed,
      });
      setReview(begun.review);
      setTextOnlyConfirmed(true);
      const approved = await api.approveReview({ scriptFingerprint: begun.review.scriptFingerprint });
      setReview(approved.review);
    } catch (caught) {
      setReviewMutationError(toMappingDisplayError(caught));
    } finally { beginBusy.current = false; setBeginPending(false); }
  }

  /**
   * A review that was never started carries no baseline to approve against.
   *
   * `loadReview` answers ENOENT with `script_fingerprint: ""` (mappings.repository.ts), the screen sent that
   * empty string straight back, and the server's first guard rejected it as a malformed request — which
   * `mappingsApi` renders as "입력 내용을 확인해 주세요". 캡틴D pressed 연결 다 했음 on a project with no
   * review yet and was told to check input they had never given. The server now names the reason
   * (`no_baseline`, CLI Round 534), but the honest move is not to send a request we know will be refused:
   * the screen has the same fact in its hand.
   */
  /* The contract's check, not a tenth copy of the pattern. This is the line that decides `baselineMissing`,
     so an anchorless copy here would have read a review with a damaged fingerprint as one that has a baseline
     — and sent the request this whole branch exists to withhold. */
  const baselineMissing = review !== null && !isSha256Hex(review.scriptFingerprint);

  async function approve() {
    if (approveBusy.current || !review) return;
    if (baselineMissing) {
      setReviewMutationError({
        code: "MAPPING_REVIEW_NO_BASELINE",
        message: "이 프로젝트는 아직 검사 기준을 잡지 않았습니다. 위의 「지금 대본 기준으로 다시 맞추기」를 먼저 눌러 주세요 — 연결한 것은 그대로 둡니다.",
      });
      return;
    }
    approveBusy.current = true;
    setApprovePending(true);
    setReviewMutationError(null);
    try {
      const response = await api.approveReview({ scriptFingerprint: review.scriptFingerprint });
      setReview(response.review);
      // The button said "다음 단계로" and then went nowhere — it only refreshed a status line that, on a
      // second visit, already read 승인됨. Nothing on screen changed, so it read as a dead button.
      if (response.review.status === "approved") onOpenImageGeneration?.();
    } catch (caught) {
      setReviewMutationError(toMappingDisplayError(caught));
    } finally {
      approveBusy.current = false;
      setApprovePending(false);
    }
  }

  const excludedCount = (mappings ?? []).filter((mapping) => mapping.status === "excluded").length;
  const filteredMappings = (mappings ?? []).filter((mapping) => {
    // Asking for 제외됨 in the status filter is an explicit request to see them, so it wins over the default.
    if (mapping.status === "excluded" && !showExcluded && statusFilter !== "excluded") return false;
    if (statusFilter && mapping.status !== statusFilter) return false;
    if (typeFilter && assets[mapping.assetId]?.assetType !== typeFilter) return false;
    if (sceneFilter && !scopeIncludesScene(mapping.sceneScope, sceneFilter)) return false;
    return true;
  });

  return (
    <section className="mt-8 max-w-5xl space-y-6">
      <header className="space-y-1.5">
        <button type="button" className="text-xs text-slate-400 hover:text-slate-300" onClick={onBack}>
          <span aria-hidden="true">←</span> 프로젝트로 돌아가기
        </button>
        <div className="flex items-center justify-between gap-3">
          <h1 className="flex items-center gap-2.5 text-2xl font-semibold text-slate-100">
          <span
            aria-hidden="true"
            className="h-2 w-2 rounded-full bg-gradient-to-br from-violet-300 to-pink-300 shadow-[0_0_6px_rgba(216,180,254,0.7)]"
          />
            참고 이미지 연결 검토
          </h1>
          <button type="button" className={outlineButton} onClick={() => void load()}>새로고침</button>
        </div>
      </header>

      {/* The old copy said these connections were made "자동으로" — nothing in this codebase auto-matches an
          Asset to a scene. Every row here was connected by hand (or migrated from the old Python data), and a
          hand-made connection is already confirmed the moment it is saved. Saying otherwise made the button
          below read as "confirm what the AI guessed", which is why it felt like a pointless second step. */}
      {/* Three stacked explanation blocks became one line plus a folded detail.
          The long version was written to answer "is 참고 이미지 the same as the Assets I picked in settings?" —
          a real question. But four paragraphs above the controls is how a screen stops being read at all, and
          the person who asked that question asked it while looking straight at the answer. The one fact that
          has to be visible is the two-channel split (settings choices arrive here on their own); the rest is
          reference material and folds. */}
      <p className="text-sm text-slate-400">
        각 장면이 어떤 이미지를 참고할지 정하는 곳입니다. 여기서 연결한 것은 <strong className="text-slate-200">그림을 만들 때 실제 이미지로 전달</strong>됩니다.
      </p>
      <details data-testid="reference-image-definition" className="rounded-xl border border-white/10 bg-slate-950/40 p-3 text-sm text-slate-400">
        <summary className="cursor-pointer text-slate-300">작품 기본 설정에서 고른 것과 무엇이 다른가</summary>
        <p className="mt-2">
          설정에서 고른 <span className="text-slate-300">주인공</span>·<span className="text-slate-300">전체 그림체</span>는
          <strong className="text-slate-200"> 이 목록에 자동으로 올라옵니다</strong> — 같은 선택이 그림에는 이미지로, 대본에는 글로 전달됩니다.
          그래서 이 화면에서 할 일은 <strong className="text-slate-200">조정</strong>입니다: 서브 캐릭터·배경·소품을 더하거나,
          특정 장면에만 붙이거나, 쓰지 않을 연결을 빼는 것.
        </p>
        <p className="mt-2">직접 연결한 것은 연결하는 순간 확정됩니다 — 다시 승인할 필요 없습니다.</p>
      </details>

      <section aria-label="참고 이미지 연결 추가" className="space-y-3 rounded-2xl border border-violet-400/25 bg-violet-500/[0.06] p-5">
        <h2 className="text-base font-semibold text-slate-100">참고 이미지 연결하기</h2>
        <p className="text-xs text-slate-400">
          이미지 보관함에서 골라 이 프로젝트의 장면에 붙입니다. 캐릭터는 <strong className="text-slate-300">폴더</strong>로
          연결하면 그 폴더의 대표 이미지가 전달됩니다.
        </p>

        <form onSubmit={(event) => void searchAssets(event)} aria-label="연결할 이미지 검색" className="flex flex-wrap items-end gap-2">
          <label className="flex flex-col gap-1 text-xs text-slate-400">
            이름으로 검색
            <input
              value={addQuery}
              onChange={(event) => setAddQuery(event.target.value)}
              placeholder="비워 두면 전체"
              className="w-56 rounded-lg border border-white/10 bg-slate-950/60 px-2.5 py-1.5 text-sm text-slate-100 focus:border-violet-400/50 focus:outline-none"
            />
          </label>
          <button type="submit" className={outlineButton} disabled={addSearchLoading}>
            {addSearchLoading ? "찾는 중…" : "검색"}
          </button>
        </form>

        <div className="flex flex-wrap items-end gap-3">
          <label className="flex flex-col gap-1 text-xs text-slate-400">
            어떤 용도로 쓰나요
            <select value={addRole} onChange={(event) => setAddRole(event.target.value)} className="rounded-lg border border-white/10 bg-slate-950/60 px-2.5 py-1.5 text-sm text-slate-100">
              <option value="character">등장인물</option>
              <option value="background">배경</option>
              <option value="object">소품</option>
              <option value="style">그림체·분위기</option>
            </select>
          </label>
          <label className="flex flex-col gap-1 text-xs text-slate-400">
            어느 장면에
            <select value={addScope} onChange={(event) => setAddScope(event.target.value as "all" | "scene")} className="rounded-lg border border-white/10 bg-slate-950/60 px-2.5 py-1.5 text-sm text-slate-100">
              <option value="all">모든 장면</option>
              {/* Withheld until the scene count is known: picking it would open a picker with nothing valid in it. */}
              <option value="scene" disabled={sceneNumbers.length === 0}>한 장면만</option>
            </select>
          </label>
          {addScope === "scene" && (
            <label className="flex flex-col gap-1 text-xs text-slate-400">
              장면 번호
              <select
                aria-label="연결할 장면 번호"
                value={addScene}
                onChange={(event) => setAddScene(Number(event.target.value) as SceneNumber)}
                className="rounded-lg border border-white/10 bg-slate-950/60 px-2.5 py-1.5 text-sm text-slate-100"
              >
                {sceneNumbers.map((number) => <option key={number} value={number}>{number}번 장면</option>)}
              </select>
            </label>
          )}
        </div>

        {addSearchError && (
          <p role="alert" data-testid="add-search-error" data-error-code={addSearchError.code} className="text-sm text-rose-400">{addSearchError.message}</p>
        )}
        {addError && (
          <p role="alert" data-testid="add-mapping-error" data-error-code={addError.code} className="text-sm text-rose-400">{addError.message}</p>
        )}
        {addResults && addResults.length === 0 && !addSearchLoading && (
          <p className="text-sm text-slate-400">검색 결과가 없습니다. 이미지 보관함에 먼저 등록해 주세요.</p>
        )}
        {addResults && addResults.length > 0 && (
          <ul aria-label="연결할 이미지 후보" className="grid gap-2 sm:grid-cols-2">
            {addResults.map((asset) => {
              // An excluded mapping is one the user turned OFF; calling it 연결됨 said the opposite. Naming
              // the two states apart was the first half of the fix; this button now also *acts*, so the row
              // that reports the state is the row that changes it.
              //
              // Both directions go through `decide`, the same call the row's own 확인/제외 buttons below make
              // — there is no delete in this API, and there should not be one here: an exclusion is the record
              // of a decision, and it is what stops `syncAutoMappings` from seeding the Asset straight back
              // (project-asset-mapping-sync.ts skips excluded asset ids). Deleting the row instead would let
              // the next Story Bible save undo the user's cancellation without telling them.
              // `mappings === null` is the list not having been read, and `(mappings ?? [])` turned that into
              // "nothing is connected": every candidate showed 연결 and pressing it created a mapping. An asset
              // the person had deliberately 제외 would be seeded straight back in — and an exclusion is exactly
              // what stops syncAutoMappings from re-adding it, so the undo would be silent and would then feed
              // the paid image generation. Unknown means the row cannot act.
              const listUnread = mappings === null;
              const existing = (mappings ?? []).find((mapping) => mapping.assetId === asset.assetId);
              const excluded = existing?.status === "excluded";
              const alreadyLinked = existing !== undefined && !excluded;
              const decisionPending = existing !== undefined && decisionPendingIds.has(existing.mappingId);
              const addPending = addPendingIds.has(asset.assetId);
              const rowError = existing ? decisionErrors[existing.mappingId] : undefined;
              return (
                <li key={asset.assetId} className="flex items-center gap-3 rounded-lg border border-white/10 bg-slate-950/40 p-2.5">
                  {asset.imageAvailable && asset.contentUrl
                    ? <img src={asset.contentUrl} alt="" className="h-12 w-12 rounded object-cover" />
                    : <span className="flex h-12 w-12 items-center justify-center rounded bg-slate-900 text-[10px] text-slate-500">{asset.isFolder ? "폴더" : "없음"}</span>}
                  <span className="min-w-0 flex-1">
                    <span className="block truncate text-sm text-slate-200">{asset.displayName}</span>
                    <span className="block text-xs text-slate-500">
                      {asset.isFolder ? `폴더 · 이미지 ${asset.childAssetIds.length}장` : "이미지 1장"}
                    </span>
                  </span>
                  <span className="flex flex-col items-end gap-0.5">
                    <button
                      type="button"
                      data-testid={`candidate-link-${asset.assetId}`}
                      className={outlineButton}
                      disabled={decisionPending || addPending || listUnread}
                      onClick={() => {
                        if (listUnread) return;
                        if (!existing) return void addMapping(asset);
                        void decide(existing.mappingId, alreadyLinked ? "exclude" : "confirm");
                      }}
                    >
                      {decisionPending
                        ? (alreadyLinked ? "취소하는 중…" : "되돌리는 중…")
                        : addPending ? "연결하는 중…"
                        : listUnread ? "확인 불가"
                        : alreadyLinked ? "연결됨"
                        : excluded ? "제외됨"
                        : "연결"}
                    </button>
                    {listUnread && (
                      <span data-testid={`candidate-link-unknown-${asset.assetId}`} className="max-w-[14rem] text-right text-[11px] text-amber-300">
                        연결 목록을 읽지 못해 이미 연결된 것인지 알 수 없습니다.
                      </span>
                    )}
                    {!listUnread && !decisionPending && !addPending && (alreadyLinked || excluded) && (
                      <span className="text-[11px] text-slate-500">
                        {alreadyLinked ? "한 번 더 누르면 연결을 취소합니다" : "한 번 더 누르면 다시 씁니다"}
                      </span>
                    )}
                    {rowError && (
                      <span
                        role="alert"
                        data-testid={`candidate-link-error-${asset.assetId}`}
                        data-error-code={rowError.code}
                        className="max-w-[14rem] text-right text-[11px] text-rose-400"
                      >
                        {rowError.message}
                      </span>
                    )}
                  </span>
                </li>
              );
            })}
          </ul>
        )}
      </section>

      <section aria-label="검토 상태" className="space-y-4 rounded-2xl border border-white/10 bg-slate-900/70 p-6">
        {reviewLoading && !review && <Spinner label="검토 상태를 불러오는 중..." />}
        {reviewError && (
          <p role="alert" data-testid="review-error" data-error-code={reviewError.code} className="text-sm text-rose-400">{reviewError.message}</p>
        )}
        {review && (
          <>
            <dl className="grid grid-cols-1 gap-x-6 gap-y-1.5 text-sm sm:grid-cols-2">
              <div><dt className="inline text-slate-400">상태: </dt><dd className="inline font-medium text-slate-100">{review.status === "approved" ? "승인됨" : "대기 중"}</dd></div>
              {review.status === "approved" && review.approvedAt && (
                <div><dt className="inline text-slate-400">승인 시각: </dt><dd className="inline font-medium text-slate-100 tabular-nums" title={review.approvedAt}>{formatDateTime(review.approvedAt)}</dd></div>
              )}
              <div className="sm:col-span-2"><dt className="inline text-slate-400">검토된 장면: </dt><dd className="inline font-medium text-slate-100">{review.reviewedScenes.join(", ") || "없음"}</dd></div>
            </dl>
            {/* Revision numbers and the script fingerprint are how the backend decides whether an approval is
                stale. Real, and worth having when something goes wrong — but nothing a person acts on, and
                four lines of hex at the top of a screen makes the screen look like a debugger. Kept, folded. */}
            <details className="text-sm">
              <summary className="cursor-pointer text-slate-400 hover:text-slate-300">자세한 기술 정보</summary>
              <dl className="mt-2 grid grid-cols-1 gap-x-6 gap-y-1.5 sm:grid-cols-2">
                <div><dt className="inline text-slate-400">Mapping Revision: </dt><dd className="inline font-medium text-slate-100">{review.mappingRevision}</dd></div>
                <div><dt className="inline text-slate-400">Script Revision: </dt><dd className="inline font-medium text-slate-100">{review.scriptRevision}</dd></div>
                <div className="sm:col-span-2"><dt className="inline text-slate-400">Fingerprint: </dt><dd className="inline break-all font-medium text-slate-100">{review.scriptFingerprint || "없음"}</dd></div>
              </dl>
            </details>
          </>
        )}
        {mappings && mappings.length === 0 && review?.status !== "approved" && (
          <div data-testid="mapping-no-images" className="space-y-2 rounded-xl border border-amber-400/30 bg-amber-500/5 p-3.5">
            <p className="text-sm text-amber-200">참고할 이미지를 하나도 연결하지 않았습니다.</p>
            <p className="text-xs text-slate-400">
              이대로 진행하면 그림은 글 설명만으로 만들어집니다. 특정 캐릭터·배경을 그대로 쓰고 싶으면 먼저 이미지를 연결해 주세요.
            </p>
            <button type="button" className={outlineButton} disabled={beginPending || approvePending} onClick={() => void proceedWithoutImages()}>
              {beginPending ? "진행하는 중…" : "참고 이미지 없이 진행하기"}
            </button>
          </div>
        )}

        {/* Rare paths. Leaving them open as the first two controls made every visit look like a form to fill in. */}
        <details className="space-y-1.5 text-sm">
          <summary className="cursor-pointer text-slate-400 hover:text-slate-300">특별한 경우</summary>
          <label className="mt-2 flex items-center gap-2 text-sm text-slate-300">
            <input type="checkbox" className="accent-violet-500" checked={textOnlyConfirmed} disabled={beginPending} onChange={(event) => setTextOnlyConfirmed(event.target.checked)} /> 이미지 없이 진행하겠습니다
          </label>
          <p className="pl-6 text-xs text-slate-500">참고할 이미지를 하나도 안 붙이고 글만으로 그림을 만들 때 켜세요. 켜면 빠진 장면 검사를 건너뜁니다.</p>
          <label className="flex items-center gap-2 text-sm text-slate-300">
            <input type="checkbox" className="accent-violet-500" checked={legacyConfirmed} disabled={beginPending} onChange={(event) => setLegacyConfirmed(event.target.checked)} /> 예전 프로젝트에서 옮겨온 연결을 그대로 쓰겠습니다
          </label>
          <p className="pl-6 text-xs text-slate-500">예전 버전에서 만들어 둔 연결이 이미 있을 때만 씁니다. 새로 만든 프로젝트라면 끈 채로 두세요.</p>
        </details>
        <div className="flex flex-wrap items-center gap-3">
          <button type="button" className={outlineButton} onClick={() => void beginReview()} disabled={beginPending}>지금 대본 기준으로 다시 맞추기</button>
          {/* This is the only way out of an unstarted review, and its hint used to name one case only —
              "대본을 고쳤다면" — so the person who had changed nothing read it as "not your case" and stayed
              stuck. `beginReview` is the same call either way: it sets the baseline the first time and resets
              it afterwards. CLI Round 536 confirmed and pinned that it does not drop existing links, so the
              sentence can say so. */}
          <span data-testid="mapping-rebase-hint" className="text-xs text-slate-500">
            {baselineMissing
              ? "이 프로젝트는 아직 검사 기준이 없습니다. 먼저 눌러 주세요 — 연결한 것은 그대로 둡니다."
              : "대본을 고쳤다면 눌러 주세요. 바뀐 대본에 맞춰 검사 기준을 새로 잡습니다. 연결한 것은 그대로 둡니다."}
          </span>
        </div>
        <div className="flex flex-wrap items-center gap-3">
          <button
            type="button"
            data-testid="approve-review-button"
            className="rounded-full bg-gradient-to-r from-violet-500 to-fuchsia-500 px-3.5 py-1.5 text-xs font-semibold text-white shadow-[0_0_16px_rgba(139,92,246,0.35)] disabled:opacity-50"
            onClick={() => void approve()}
            disabled={approvePending || !review}
          >
            {approvePending ? "검사하는 중…" : review?.status === "approved" ? "다시 검사하고 다음 단계로" : "연결 다 했음 · 다음 단계로"}
          </button>
          {/* Already approved once: re-running the check is a choice, not a requirement. Moving on needs its
              own button, or the only way forward is one whose label implies work that is already done. */}
          {review?.status === "approved" && onOpenImageGeneration && (
            <button
              type="button"
              data-testid="skip-to-image-generation"
              className={outlineButton}
              disabled={approvePending}
              onClick={() => onOpenImageGeneration()}
            >
              그냥 다음 단계로
            </button>
          )}
          <span className="text-xs text-slate-500">
            {review?.status === "approved"
              ? "이미 승인된 상태입니다. 연결을 고쳤다면 다시 검사하고, 아니면 그냥 넘어가면 됩니다."
              : "빠진 장면이 없는지 검사하고 다음 단계로 넘어갑니다."}
          </span>
        </div>
        {reviewMutationError && (
          <div role="alert" data-testid="review-mutation-error" data-error-code={reviewMutationError.code}>
            <p className="text-sm text-rose-400">
              {reviewMutationError.message}
              {errorDetailLabel(reviewMutationError.details) && <span> ({errorDetailLabel(reviewMutationError.details)})</span>}
            </p>
            {reviewMutationError.code === "ASSET_MAPPING_APPROVAL_BLOCKED" && (
              <p data-testid="review-blocked-reason" className="mt-1 text-sm text-amber-300">
                {blockedReason(mappings, reviewMutationError.details)}
              </p>
            )}
          </div>
        )}
      </section>

      <form onSubmit={(event) => event.preventDefault()} className="flex flex-wrap gap-4">
        <label className="text-sm text-slate-300">상태
          <select className={`block ${selectClassName}`} value={statusFilter} onChange={(event) => setStatusFilter(event.target.value as AssetMappingStatus | "")}>
            <option value="">전체</option>
            {Object.entries(STATUS_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}
          </select>
        </label>
        <label className="text-sm text-slate-300">유형
          <select className={`block ${selectClassName}`} value={typeFilter} onChange={(event) => setTypeFilter(event.target.value as AssetType | "")}>
            <option value="">전체</option>
            {Object.entries(TYPE_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}
          </select>
        </label>
        <label className="text-sm text-slate-300">장면
          <select
            className={`block ${selectClassName}`}
            value={sceneFilter}
            disabled={sceneNumbers.length === 0}
            onChange={(event) => setSceneFilter(event.target.value ? (Number(event.target.value) as SceneNumber) : "")}
          >
            <option value="">전체</option>
            {sceneNumbers.map((number) => <option key={number} value={number}>{number}</option>)}
          </select>
        </label>
      </form>

      {mappingsLoading && !mappings && <Spinner label="Mapping을 불러오는 중..." />}
      {mappingsError && (
        <>
          <p role="alert" data-testid="mappings-error" data-error-code={mappingsError.code} className="text-sm text-rose-400">{mappingsError.message}</p>
          {MAPPING_FILE_UNREADABLE.has(mappingsError.code) && (
            <p data-testid="mapping-file-recovery" className={recoveryNote}>
              다시 열어도 같은 화면이 나옵니다. 다만 <code className={fileName}>asset_mappings.json</code> 은 지우지 마세요 —
              지우면 직접 연결해 둔 참고 이미지가 전부 사라지고, 되돌릴 버튼은 없습니다. 백업해 둔 파일이 있으면
              그것으로 되돌리는 게 가장 안전합니다.
            </p>
          )}
        </>
      )}
      {excludedCount > 0 && statusFilter !== "excluded" && (
        <p className="text-xs text-slate-500">
          쓰지 않기로 한 연결 {excludedCount}개는 {showExcluded ? "함께 보이고 있습니다" : "목록에서 숨겼습니다"}.{" "}
          <button
            type="button"
            data-testid="toggle-excluded"
            className="text-slate-300 underline underline-offset-2 hover:text-slate-100"
            onClick={() => setShowExcluded((shown) => !shown)}
          >
            {showExcluded ? "숨기기" : "보기"}
          </button>
        </p>
      )}
      {mappings && mappings.length === 0 && !mappingsLoading && <p className="text-slate-400">등록된 참고 이미지 연결이 없습니다.</p>}

      {mappings && mappings.length > 0 && (
        <ul aria-label="Mapping 목록" className="space-y-3">
          {filteredMappings.map((mapping) => {
            const asset = assets[mapping.assetId];
            const assetError = assetErrors[mapping.assetId];
            const decisionBusyNow = decisionPendingIds.has(mapping.mappingId);
            const snapshotBusyNow = snapshotPendingIds.has(mapping.mappingId);
            return (
              <li key={mapping.mappingId} className="space-y-2 rounded-2xl border border-white/10 bg-slate-900/70 p-4">
                {asset ? (
                  <div className="flex items-baseline gap-2">
                    {asset.imageAvailable && asset.contentUrl && (
                      <img src={asset.contentUrl} alt="" className="mr-1 h-20 w-32 flex-shrink-0 rounded-xl border border-white/10 object-cover" />
                    )}
                    <strong className="font-semibold text-slate-100">{asset.displayName}</strong>
                    <span className="text-sm text-slate-400"> · {TYPE_LABELS[asset.assetType]}</span>
                  </div>
                ) : assetError ? (
                  <p role="alert" data-testid={`asset-error-${mapping.mappingId}`} data-error-code={assetError.code} className="text-sm text-rose-400">{assetError.message}</p>
                ) : (
                  <Spinner label="에셋 정보를 불러오는 중..." />
                )}
                <div className="space-y-0.5 text-sm text-slate-400">
                  {/* `auto` means the link came from what was chosen in 프로젝트 설정, not from this screen.
                      That difference is worth showing plainly: removing such a row here only affects this
                      list, while the settings choice it came from stays where it was. Rows made by hand or
                      migrated from the old data keep their existing, quieter treatment. */}
                  {mapping.assignmentSource === "auto" && (
                    <p data-testid={`mapping-origin-${mapping.mappingId}`} className="text-xs text-violet-300">
                      프로젝트 설정에서 자동으로 연결된 항목입니다.
                    </p>
                  )}
                  <p>역할: {mapping.usageRole}</p>
                  <p>범위: {scopeLabel(mapping.sceneScope)}</p>
                  <p className={STATUS_TEXT_TONE[mapping.status]}>상태: {STATUS_LABELS[mapping.status]}</p>
                  {/* Mapping id, assignment source and version policy are storage-level facts. They matter when
                      something has to be matched up by hand; they are noise on every other row. */}
                  <details>
                    <summary className="cursor-pointer text-xs text-slate-500 hover:text-slate-400">자세한 기술 정보</summary>
                    <div className="mt-1 space-y-0.5 text-xs">
                      <p>Mapping ID: {mapping.mappingId}</p>
                      <p>출처: {mapping.assignmentSource}</p>
                      <p>버전 정책: {mapping.versionPolicy}{mapping.pinnedVersion !== null ? ` (v${mapping.pinnedVersion})` : ""}</p>
                      <p>스냅샷: {mapping.snapshot ? `v${mapping.snapshot.sourceVersion} · ${mapping.snapshot.sha256.slice(0, 12)}...` : "없음"}</p>
                    </div>
                  </details>
                </div>
                <div className="flex flex-wrap items-center gap-2 pt-1">
                  {/* A row you connected yourself arrives already confirmed, so this button would change nothing
                      — offering it is what made the screen feel like it was asking twice. It stays for rows that
                      really are unresolved (migrated data, or a mapping invalidated by a script change). */}
                  {mapping.status !== "confirmed" && (
                    <button type="button" className={`${outlineButton} border-emerald-400/30 text-emerald-300`} onClick={() => void decide(mapping.mappingId, "confirm")} disabled={decisionBusyNow}>확인</button>
                  )}
                  <button type="button" className={`${outlineButton} border-rose-400/30 text-rose-300`} onClick={() => void decide(mapping.mappingId, "exclude")} disabled={decisionBusyNow}>제외</button>
                  <button type="button" className={outlineButton} onClick={() => void createSnapshot(mapping.mappingId)} disabled={snapshotBusyNow}>스냅샷 생성</button>
                  <span className="text-xs text-slate-500">
                    {mapping.status === "confirmed" ? "제외: 이 연결을 쓰지 않음" : "확인: 이 연결을 그대로 사용 · 제외: 이 연결을 쓰지 않음"} · 스냅샷 생성: 지금 이미지 버전을 이 장면에 고정
                  </span>
                </div>
                {decisionErrors[mapping.mappingId] && (
                  <p role="alert" data-testid={`decision-error-${mapping.mappingId}`} data-error-code={decisionErrors[mapping.mappingId]!.code} className="text-sm text-rose-400">
                    {decisionErrors[mapping.mappingId]!.message}
                  </p>
                )}
                {snapshotErrors[mapping.mappingId] && (
                  <p role="alert" data-testid={`snapshot-error-${mapping.mappingId}`} data-error-code={snapshotErrors[mapping.mappingId]!.code} className="text-sm text-rose-400">
                    {snapshotErrors[mapping.mappingId]!.message}
                  </p>
                )}
              </li>
            );
          })}
        </ul>
      )}
    </section>
  );
}
