import * as fs from "node:fs/promises";
import * as path from "node:path";
import { Injectable } from "@nestjs/common";
import type { ApproveLongEpisodeScriptRequest, ApproveLongEpisodeScriptResponse, GenerateLongEpisodeScriptRequest, GenerateLongEpisodeScriptResponse, GetLongEpisodeResponse, LongEpisodeDetail, LongEpisodeOutline, LongEpisodeScene, LongEpisodeScript, LongEpisodeStatus, SceneNumber, UpdateLongEpisodeScriptRequest, UpdateLongEpisodeScriptResponse } from "@ai-animation-studio/shared";
import { atomicWriteUtf8File } from "../projects/atomic-file.js";
import { isSafeProjectId, resolveSafeProjectDirectory } from "../projects/project-id.js";
import { longEpisodeNotFound, longEpisodeScriptExists, longEpisodeScriptNotAllowed, longInvalidData, longInvalidRequest, longMalformed, longNotFound, longStorageError, longUnsafeId } from "./long-project-api.error.js";
import { LongProjectsService } from "./long-projects.service.js";

const snakeKeys = ["number", "description", "visual_action", "start_motion", "main_motion", "end_motion", "shot_size", "camera_angle", "composition", "lens_feel", "focus_subject", "camera_motion", "environment_motion", "motion_speed", "motion_intensity", "expression_change", "continuity_hint"] as const;
const camelKeys = ["number", "description", "visualAction", "startMotion", "mainMotion", "endMotion", "shotSize", "cameraAngle", "composition", "lensFeel", "focusSubject", "cameraMotion", "environmentMotion", "motionSpeed", "motionIntensity", "expressionChange", "continuityHint"] as const;
type StoredEpisode = { episode_id: string; number: number; title: string; summary: string; core_event: string; conflict: string; cliffhanger: string; next_connection: string; duration_seconds: number; scene_count: number; approved: boolean; state: LongEpisodeStatus; script: Record<string, unknown>; script_history: unknown[]; script_revision: number; outline: Record<string, unknown>; updated_at: string };

const asObject = (value: unknown, error = longInvalidData): Record<string, unknown> => { if (!value || typeof value !== "object" || Array.isArray(value)) throw error(); return value as Record<string, unknown>; };
const asText = (value: unknown, error = longInvalidData): string => { if (typeof value !== "string") throw error(); return value.trim(); };
const asNumber = (value: unknown, error = longInvalidData): number => { if (!Number.isInteger(value)) throw error(); return value as number; };
const statuses: readonly LongEpisodeStatus[] = ["planned", "outline_ready", "script_review", "script_approved", "waiting_for_asset_mapping_review", "asset_mapping_approved", "generating_images", "images_ready", "images_review", "waiting_for_video_confirmation", "videos_generating", "videos_ready", "videos_review", "videos_approved", "interrupted"];

@Injectable()
export class EpisodeScriptsService {
  private readonly projects: LongProjectsService;
  constructor(private readonly projectsRoot: string) { this.projects = new LongProjectsService(projectsRoot); }

  private root(projectId: string): string { if (!isSafeProjectId(projectId)) throw longUnsafeId(); return path.join(resolveSafeProjectDirectory(this.projectsRoot, projectId), "long_story"); }
  private files(projectId: string, number: number) { const root = this.root(projectId); const episode = path.join(root, `Episode${String(number).padStart(2, "0")}`); return { root, project: path.join(root, "project.json"), outlines: path.join(root, "episode_outlines.json"), bible: path.join(root, "story_bible.json"), episode, episodeProject: path.join(episode, "project.json"), outline: path.join(episode, "outline.json"), script: path.join(episode, "script.json") }; }
  private async json(file: string): Promise<unknown> { try { return JSON.parse(await fs.readFile(file, "utf8")); } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") throw longNotFound(); if (error instanceof SyntaxError) throw longMalformed(); throw longStorageError(); } }
  private async outline(projectId: string, number: number): Promise<LongEpisodeOutline> {
    if (!Number.isInteger(number) || number < 1) throw longEpisodeNotFound();
    const raw = await this.json(this.files(projectId, number).outlines);
    if (!Array.isArray(raw)) throw longInvalidData();
    if (number > raw.length) throw longEpisodeNotFound();
    const item = raw[number - 1]; const d = asObject(item);
    if (d.episode_number !== number || !statuses.includes(d.status as LongEpisodeStatus) || ["title", "summary", "main_event", "conflict", "cliffhanger", "next_episode_hook"].some((key) => typeof d[key] !== "string")) throw longInvalidData();
    return { episodeNumber: number, title: d.title as string, summary: d.summary as string, mainEvent: d.main_event as string, conflict: d.conflict as string, cliffhanger: d.cliffhanger as string, nextEpisodeHook: d.next_episode_hook as string, status: d.status as LongEpisodeStatus };
  }
  private parseScript(value: unknown, sceneCount: number, error = longInvalidData): LongEpisodeScript {
    const d = asObject(value, error); if (Object.keys(d).length !== 4 || typeof d.title !== "string" || typeof d.synopsis !== "string" || typeof d.ending !== "string" || !Array.isArray(d.scenes) || d.scenes.length !== sceneCount) throw error();
    const scenes = d.scenes.map((item, index) => { const scene = asObject(item, error); const sourceKeys = "visualAction" in scene ? camelKeys : snakeKeys; if (Object.keys(scene).length !== sourceKeys.length || sourceKeys.some((key) => !(key in scene)) || scene.number !== index + 1 || sourceKeys.slice(1).some((key) => typeof scene[key] !== "string") || !String(scene.description).trim()) throw error(); return Object.fromEntries(camelKeys.map((key, itemIndex) => [key, scene[sourceKeys[itemIndex]!]])) as unknown as LongEpisodeScene; });
    return { title: d.title, synopsis: d.synopsis, ending: d.ending, scenes };
  }
  private storedScript(script: LongEpisodeScript): Record<string, unknown> { return { title: script.title, synopsis: script.synopsis, ending: script.ending, scenes: script.scenes.map((scene) => Object.fromEntries(snakeKeys.map((key, index) => [key, scene[camelKeys[index]!]]))) }; }
  private async stored(projectId: string, outline: LongEpisodeOutline): Promise<StoredEpisode> {
    const files = this.files(projectId, outline.episodeNumber);
    try { return this.parseStored(await this.json(files.episodeProject), outline); } catch (error) { if (!(error instanceof Error) || !("getStatus" in error) || (error as { getStatus(): number }).getStatus() !== 404) throw error; const projectSettings = (await this.projects.get(projectId)).project.settings; return { episode_id: `${projectId}-episode-${outline.episodeNumber}`, number: outline.episodeNumber, title: outline.title, summary: outline.summary, core_event: outline.mainEvent, conflict: outline.conflict, cliffhanger: outline.cliffhanger, next_connection: outline.nextEpisodeHook, duration_seconds: projectSettings.episodeDurationSeconds, scene_count: projectSettings.sceneCount, approved: false, state: outline.status, script: {}, script_history: [], script_revision: 0, outline: { episode_number: outline.episodeNumber, title: outline.title, summary: outline.summary, main_event: outline.mainEvent, conflict: outline.conflict, cliffhanger: outline.cliffhanger, next_episode_hook: outline.nextEpisodeHook }, updated_at: new Date().toISOString() }; }
  }
  /** A project stored before scene_count existed (per-episode, snapshotted the same way duration_seconds already was) has no such field — falls back to 6, matching every Episode created back then. */
  private parseStored(value: unknown, outline: LongEpisodeOutline): StoredEpisode { const d = asObject(value); if (d.number !== outline.episodeNumber || !statuses.includes(d.state as LongEpisodeStatus) || typeof d.approved !== "boolean" || !Array.isArray(d.script_history) || !Number.isInteger(d.script_revision) || Number(d.script_revision) < 0) throw longInvalidData(); const result: StoredEpisode = { episode_id: asText(d.episode_id), number: outline.episodeNumber, title: asText(d.title), summary: asText(d.summary), core_event: asText(d.core_event), conflict: asText(d.conflict), cliffhanger: asText(d.cliffhanger), next_connection: asText(d.next_connection), duration_seconds: asNumber(d.duration_seconds), scene_count: Number.isInteger(d.scene_count) ? d.scene_count as number : 6, approved: d.approved, state: d.state as LongEpisodeStatus, script: asObject(d.script), script_history: d.script_history, script_revision: d.script_revision as number, outline: asObject(d.outline), updated_at: asText(d.updated_at) }; return result; }
  private toApi(outline: LongEpisodeOutline, stored: StoredEpisode): LongEpisodeDetail { const script = Object.keys(stored.script).length ? this.parseScript(stored.script, stored.scene_count) : undefined; return { ...outline, status: stored.state, approved: stored.approved, scriptRevision: stored.script_revision, ...(script ? { script } : {}), scriptHistoryCount: stored.script_history.length }; }
  private async save(projectId: string, outline: LongEpisodeOutline, stored: StoredEpisode): Promise<LongEpisodeDetail> { const files = this.files(projectId, outline.episodeNumber); const outlines = await this.json(files.outlines); if (!Array.isArray(outlines)) throw longInvalidData(); const copy = [...outlines]; const current = asObject(copy[outline.episodeNumber - 1]); current.status = stored.state; copy[outline.episodeNumber - 1] = current; try { await fs.mkdir(files.episode, { recursive: true }); await Promise.all([atomicWriteUtf8File(files.episodeProject, JSON.stringify(stored, null, 2)), atomicWriteUtf8File(files.outline, JSON.stringify(stored.outline, null, 2)), atomicWriteUtf8File(files.script, JSON.stringify(stored.script, null, 2)), atomicWriteUtf8File(files.outlines, JSON.stringify(copy, null, 2))]); } catch { throw longStorageError(); } return this.toApi({ ...outline, status: stored.state }, stored); }
  private async bibleContext(projectId: string): Promise<string> { const bible = asObject(await this.json(this.files(projectId, 1).bible)); const names = ["characters", "locations", "props"].flatMap((collection) => Array.isArray(bible[collection]) ? bible[collection].map((item) => asObject(item).name).filter((name): name is string => typeof name === "string" && Boolean(name.trim())) : []); return names.join(", "); }
  private async continuityContext(projectId: string, episodeNumber: number): Promise<Record<string, unknown>> { const recent: unknown[] = []; const older: unknown[] = []; for (let number = 1; number < episodeNumber; number += 1) { try { const raw = asObject(await this.json(path.join(this.files(projectId, number).episode, "continuity.json"))); const record = { episodeNumber: number, summary: typeof raw.episode_summary === "string" ? raw.episode_summary : "", events: Array.isArray(raw.events) ? raw.events.filter((value): value is string => typeof value === "string") : [], characterChanges: Array.isArray(raw.character_changes) ? raw.character_changes.filter((value) => value && typeof value === "object" && !Array.isArray(value)) : [], nextActions: Array.isArray(raw.next_actions) ? raw.next_actions.filter((value): value is string => typeof value === "string") : [] }; (number >= episodeNumber - 3 ? recent : older).push(record); } catch (error) { if (!(error instanceof Error && "getStatus" in error && (error as { getStatus(): number }).getStatus() === 404)) throw error; } } return { recentContinuity: recent, olderCompressedSummaries: older.map((value) => ({ episodeNumber: (value as { episodeNumber: number }).episodeNumber, summary: (value as { summary: string }).summary })) }; }
  private generated(outline: LongEpisodeOutline, bibleNames: string, continuity: Record<string, unknown>, sceneCount: number): LongEpisodeScript { const subject = outline.title || `Episode ${outline.episodeNumber}`; const latest = (continuity.recentContinuity as Array<{ summary: string }>).at(-1)?.summary; const scenes = Array.from({ length: sceneCount }, (_, index) => { const number = index + 1; return { number: number as SceneNumber, description: `${subject} scene ${number}: ${outline.summary || outline.mainEvent || "the episode progresses"}.`, visualAction: `The central action develops in scene ${number}.`, startMotion: "A still opening pose shifts into motion.", mainMotion: "The character advances the episode conflict.", endMotion: "The movement settles into the next scene.", shotSize: "medium shot", cameraAngle: "eye level", composition: "centered subject with readable background", lensFeel: "natural perspective", focusSubject: bibleNames || subject, cameraMotion: "gentle forward movement", environmentMotion: "subtle ambient movement", motionSpeed: "normal", motionIntensity: "moderate", expressionChange: "focused to hopeful", continuityHint: number === 1 && latest ? `Continue from prior Episode: ${latest}` : number === 1 ? "Establish the opening visual state." : "Continue the previous scene's ending pose and direction." }; }); return { title: `${subject} — Local Episode Script`, synopsis: `A local ${sceneCount}-scene draft for ${subject}.${latest ? ` It continues: ${latest}` : ""}`, ending: outline.cliffhanger || "The episode reaches its next turning point.", scenes }; }
  async get(projectId: string, number: number): Promise<GetLongEpisodeResponse> { const outline = await this.outline(projectId.trim(), number); return { episode: this.toApi(outline, await this.stored(projectId.trim(), outline)) }; }
  async generate(projectId: string, number: number, request: GenerateLongEpisodeScriptRequest): Promise<GenerateLongEpisodeScriptResponse> { const id = projectId.trim(); const outline = await this.outline(id, number); const stored = await this.stored(id, outline); if (!["outline_ready", "script_review", "script_approved"].includes(stored.state)) throw longEpisodeScriptNotAllowed(); if (Object.keys(stored.script).length && request?.regenerate !== true) throw longEpisodeScriptExists(); if (Object.keys(stored.script).length) stored.script_history.push({ created_at: new Date().toISOString(), source: "before_regeneration", script: stored.script }); const continuity = await this.continuityContext(id, number); const script = this.generated(outline, await this.bibleContext(id), continuity, stored.scene_count); stored.script = this.storedScript(script); stored.script_history.push({ created_at: new Date().toISOString(), source: "local_fake_generation", script: stored.script, continuity_context: continuity }); stored.script_revision += 1; stored.approved = false; stored.state = "script_review"; stored.updated_at = new Date().toISOString(); return { episode: await this.save(id, outline, stored) }; }
  async update(projectId: string, number: number, request: UpdateLongEpisodeScriptRequest): Promise<UpdateLongEpisodeScriptResponse> { const id = projectId.trim(); const outline = await this.outline(id, number); const stored = await this.stored(id, outline); if (stored.state !== "script_review" || !Object.keys(stored.script).length) throw longEpisodeScriptNotAllowed(); const script = this.parseScript(request?.script, stored.scene_count, longInvalidRequest); stored.script_history.push({ created_at: new Date().toISOString(), source: "before_user_edit", script: stored.script }); stored.script = this.storedScript(script); stored.script_revision += 1; stored.approved = false; stored.updated_at = new Date().toISOString(); return { episode: await this.save(id, outline, stored) }; }
  async approve(projectId: string, number: number, request: ApproveLongEpisodeScriptRequest): Promise<ApproveLongEpisodeScriptResponse> { const id = projectId.trim(); const outline = await this.outline(id, number); const stored = await this.stored(id, outline); if (request?.approved !== true || stored.state !== "script_review" || !Object.keys(stored.script).length) throw longEpisodeScriptNotAllowed(); stored.approved = true; stored.state = "script_approved"; stored.updated_at = new Date().toISOString(); return { episode: await this.save(id, outline, stored) }; }
}
