import * as fs from "node:fs/promises";
import * as path from "node:path";
import { Injectable } from "@nestjs/common";
import type { GetLongEpisodeContinuityResponse, LongEpisodeContinuityMemory, LongEpisodeDetail, LongEpisodeStatus, SaveLongEpisodeContinuityRequest, SaveLongEpisodeContinuityResponse } from "@ai-animation-studio/shared";
import { atomicWriteUtf8File } from "../projects/atomic-file.js";
import { isSafeProjectId, resolveSafeProjectDirectory } from "../projects/project-id.js";
import { longEpisodeContinuityNotAllowed, longEpisodeNotFound, longInvalidData, longInvalidRequest, longMalformed, longNotFound, longStorageError, longUnsafeId } from "./long-project-api.error.js";
import { toApiEpisodeScript } from "./episode-script-format.js";
import { withoutStaleEpisodeRecoveryWarnings } from "./orphaned-episode-generation-recovery.service.js";

const eligible: readonly LongEpisodeStatus[] = ["waiting_for_video_confirmation", "videos_generating", "videos_ready", "videos_review", "videos_approved", "rendering", "completed"];
const states: readonly LongEpisodeStatus[] = ["planned", "outline_ready", "script_review", "script_approved", "waiting_for_asset_mapping_review", "asset_mapping_approved", "generating_images", "images_ready", "images_review", "waiting_for_video_confirmation", "videos_generating", "videos_ready", "videos_review", "videos_approved", "interrupted", "rendering", "completed", "failed"];
const memoryStrings = ["episodeSummary", "timeElapsed", "userEdits"] as const;
const memoryLists = ["events", "appearedCharacterIds", "appearedLocationIds", "resolvedConflicts", "newConflicts", "revealedSecretIds", "remainingSecretIds", "newForeshadowingIds", "resolvedForeshadowingIds", "nextActions", "worldChanges"] as const;
const changeLists = ["characterChanges", "itemChanges"] as const;
type StoredEpisode = Record<string, unknown> & { number: number; state: LongEpisodeStatus; approved: boolean; script_revision: number; updated_at: string; };
const object = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === "object" && !Array.isArray(value);
const text = (value: unknown, limit = 4000): string | undefined => typeof value === "string" && value.trim().length <= limit ? value.trim() : undefined;

@Injectable()
export class EpisodeContinuityService {
  constructor(private readonly projectsRoot: string) {}

  private files(projectId: string, number: number) { if (!isSafeProjectId(projectId)) throw longUnsafeId(); const root = path.join(resolveSafeProjectDirectory(this.projectsRoot, projectId), "long_story"); const episode = path.join(root, `Episode${String(number).padStart(2, "0")}`); return { root, outlines: path.join(root, "episode_outlines.json"), project: path.join(episode, "project.json"), continuity: path.join(episode, "continuity.json") }; }
  private async json(file: string): Promise<unknown> { try { return JSON.parse(await fs.readFile(file, "utf8")); } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") throw longNotFound(); if (error instanceof SyntaxError) throw longMalformed(); throw longStorageError(); } }
  private async episode(id: string, number: number): Promise<StoredEpisode> { if (!Number.isInteger(number) || number < 1) throw longEpisodeNotFound(); const files = this.files(id, number); const outlines = await this.json(files.outlines); if (!Array.isArray(outlines) || number > outlines.length || !object(outlines[number - 1]) || outlines[number - 1].episode_number !== number) throw longEpisodeNotFound(); const raw = await this.json(files.project); if (!object(raw) || raw.number !== number || !states.includes(raw.state as LongEpisodeStatus) || typeof raw.approved !== "boolean" || !Number.isInteger(raw.script_revision) || typeof raw.updated_at !== "string") throw longInvalidData(); return raw as StoredEpisode; }
  private detail(episode: StoredEpisode): LongEpisodeDetail { const script = toApiEpisodeScript(episode.script); const warnings = withoutStaleEpisodeRecoveryWarnings(Array.isArray(episode.warnings) ? episode.warnings.filter((item): item is string => typeof item === "string") : [], episode.state); return { episodeNumber: episode.number, title: String(episode.title), summary: String(episode.summary), mainEvent: String(episode.core_event), conflict: String(episode.conflict), cliffhanger: String(episode.cliffhanger), nextEpisodeHook: String(episode.next_connection), status: episode.state, approved: episode.approved, scriptRevision: episode.script_revision, ...(script ? { script } : {}), scriptHistoryCount: Array.isArray(episode.script_history) ? episode.script_history.length : 0, ...(warnings.length > 0 ? { warnings } : {}) }; }
  private parse(value: unknown, expectedNumber: number, request = false): LongEpisodeContinuityMemory { const source = request ? (object(value) && Object.keys(value).length === 1 && object(value.memory) ? value.memory : undefined) : value; if (!object(source)) throw request ? longInvalidRequest("Episode Continuity Memory request is invalid.") : longInvalidData(); const expected = new Set(request ? [...memoryStrings, ...memoryLists, ...changeLists] : ["episodeNumber", "updatedAt", ...memoryStrings, ...memoryLists, ...changeLists]); if (Object.keys(source).length !== expected.size || Object.keys(source).some((key) => !expected.has(key)) || (!request && (source.episodeNumber !== expectedNumber || typeof source.updatedAt !== "string"))) throw request ? longInvalidRequest("Episode Continuity Memory request is invalid.") : longInvalidData(); const invalid = request ? longInvalidRequest("Episode Continuity Memory request is invalid.") : longInvalidData(); const updatedAt = request ? new Date().toISOString() : text(source.updatedAt, 100); if (!updatedAt) throw invalid; const result: Record<string, unknown> = { episodeNumber: expectedNumber, updatedAt };
    for (const key of memoryStrings) { const value = text(source[key]); if (value === undefined) throw invalid; result[key] = value; }
    for (const key of memoryLists) { const value = source[key]; if (!Array.isArray(value) || value.length > 100 || value.some((item) => text(item, 1000) === undefined)) throw invalid; result[key] = value.map((item) => text(item, 1000)!); }
    for (const key of changeLists) { const value = source[key]; if (!Array.isArray(value) || value.length > 100 || value.some((item) => !object(item) || JSON.stringify(item).length > 8000)) throw invalid; result[key] = value; }
    return result as unknown as LongEpisodeContinuityMemory; }
  private stored(memory: LongEpisodeContinuityMemory): Record<string, unknown> { return { episode_number: memory.episodeNumber, episode_summary: memory.episodeSummary, events: memory.events, appeared_character_ids: memory.appearedCharacterIds, character_changes: memory.characterChanges, appeared_location_ids: memory.appearedLocationIds, item_changes: memory.itemChanges, resolved_conflicts: memory.resolvedConflicts, new_conflicts: memory.newConflicts, revealed_secret_ids: memory.revealedSecretIds, remaining_secret_ids: memory.remainingSecretIds, new_foreshadowing_ids: memory.newForeshadowingIds, resolved_foreshadowing_ids: memory.resolvedForeshadowingIds, next_actions: memory.nextActions, time_elapsed: memory.timeElapsed, world_changes: memory.worldChanges, user_edits: memory.userEdits, updated_at: memory.updatedAt }; }
  private fromStored(value: unknown, number: number): LongEpisodeContinuityMemory { if (!object(value)) throw longInvalidData(); return this.parse({ episodeNumber: value.episode_number, updatedAt: value.updated_at, episodeSummary: value.episode_summary, events: value.events, appearedCharacterIds: value.appeared_character_ids, characterChanges: value.character_changes, appearedLocationIds: value.appeared_location_ids, itemChanges: value.item_changes, resolvedConflicts: value.resolved_conflicts, newConflicts: value.new_conflicts, revealedSecretIds: value.revealed_secret_ids, remainingSecretIds: value.remaining_secret_ids, newForeshadowingIds: value.new_foreshadowing_ids, resolvedForeshadowingIds: value.resolved_foreshadowing_ids, nextActions: value.next_actions, timeElapsed: value.time_elapsed, worldChanges: value.world_changes, userEdits: value.user_edits }, number); }
  async get(projectId: string, number: number): Promise<GetLongEpisodeContinuityResponse> { const id = projectId.trim(); await this.episode(id, number); try { return { memory: this.fromStored(await this.json(this.files(id, number).continuity), number) }; } catch (error) { if (error instanceof Error && "getStatus" in error && (error as { getStatus(): number }).getStatus() === 404) return { memory: null }; throw error; } }
  async save(projectId: string, number: number, request: SaveLongEpisodeContinuityRequest): Promise<SaveLongEpisodeContinuityResponse> { const id = projectId.trim(); const current = await this.episode(id, number); if (!eligible.includes(current.state)) throw longEpisodeContinuityNotAllowed(); const memory = this.parse(request, number, true); try { await atomicWriteUtf8File(this.files(id, number).continuity, JSON.stringify(this.stored(memory), null, 2)); } catch { throw longStorageError(); } let nextEpisode: LongEpisodeDetail | null = null; try { nextEpisode = this.detail(await this.episode(id, number + 1)); } catch (error) { if (!(error instanceof Error && "getStatus" in error && (error as { getStatus(): number }).getStatus() === 404)) throw error; } return { memory, nextEpisode }; }
}
