import * as crypto from "node:crypto";
import * as fs from "node:fs/promises";
import * as path from "node:path";
import { Injectable } from "@nestjs/common";
import type { ApproveLongProjectOutlineRequest, ApproveLongProjectOutlineResponse, CreateLongProjectOutlinePreviewResponse, CreateLongProjectRequest, CreateLongProjectResponse, GetLongProjectResponse, GetLongProjectSettingsResponse, ListLongProjectsResponse, LongEpisodeOutline, LongProject, LongProjectSettings, LongProjectSummary, UpdateLongProjectSettingsRequest, UpdateLongProjectSettingsResponse } from "@ai-animation-studio/shared";
import { atomicWriteUtf8File } from "../projects/atomic-file.js";
import { isSafeProjectId, resolveSafeProjectDirectory } from "../projects/project-id.js";
import { longExists, longInvalidData, longInvalidRequest, longMalformed, longNotFound, longOutlineNotAllowed, longOutlineStale, longStorageError, longUnsafeId } from "./long-project-api.error.js";

const MAX_EPISODES = Number(process.env.APP_MAX_LONG_PROJECT_EPISODES ?? "60");
const settingKeys = ["title", "logline", "overview", "genre", "tone", "theme", "episodeCount", "episodeDurationSeconds", "platform", "aspectRatio", "audience", "notes", "startingState", "midpoint", "endingDirection", "storyFlowSummary"] as const;
type Stored = { project_id: string; project_type: "long_story_project"; title: string; logline: string; overview: string; genre: string; tone: string; theme: string; episode_count: number; episode_duration_seconds: number; platform: "YouTube Shorts" | "YouTube"; aspect_ratio: "9:16" | "16:9"; audience: string; notes: string; starting_state: string; midpoint: string; ending_direction: string; story_flow_summary: string; created_at: string; updated_at: string; outline_status: "planned" | "outline_ready"; outline_prompt_request?: { prompt_sha256: string; prompt: string; approved_at: string; modified: boolean }; };
const object = (value: unknown): Record<string, unknown> => { if (!value || typeof value !== "object" || Array.isArray(value)) throw longInvalidRequest(); return value as Record<string, unknown>; };
const text = (value: unknown, required = false): string => { if (typeof value !== "string") throw longInvalidRequest(); const result = value.trim(); if (required && !result) throw longInvalidRequest(); return result; };
function settings(value: unknown): LongProjectSettings { const data = object(value); if (Object.keys(data).some((key) => !settingKeys.includes(key as typeof settingKeys[number]))) throw longInvalidRequest("Unknown long-project setting."); const title = text(data.title, true); const logline = text(data.logline, true); const episodeCount = data.episodeCount; const duration = data.episodeDurationSeconds; if (!Number.isInteger(episodeCount) || (episodeCount as number) < 1 || (episodeCount as number) > MAX_EPISODES || !Number.isInteger(duration) || (duration as number) <= 0 || (data.platform !== "YouTube Shorts" && data.platform !== "YouTube") || (data.aspectRatio !== "9:16" && data.aspectRatio !== "16:9")) throw longInvalidRequest(); return { title, logline, overview: text(data.overview), genre: text(data.genre), tone: text(data.tone), theme: text(data.theme), episodeCount: episodeCount as number, episodeDurationSeconds: duration as number, platform: data.platform, aspectRatio: data.aspectRatio, audience: text(data.audience), notes: text(data.notes), startingState: text(data.startingState), midpoint: text(data.midpoint), endingDirection: text(data.endingDirection), storyFlowSummary: text(data.storyFlowSummary) }; }
function toSettings(s: Stored): LongProjectSettings { return { title: s.title, logline: s.logline, overview: s.overview, genre: s.genre, tone: s.tone, theme: s.theme, episodeCount: s.episode_count, episodeDurationSeconds: s.episode_duration_seconds, platform: s.platform, aspectRatio: s.aspect_ratio, audience: s.audience, notes: s.notes, startingState: s.starting_state, midpoint: s.midpoint, endingDirection: s.ending_direction, storyFlowSummary: s.story_flow_summary }; }
function setStored(id: string, s: LongProjectSettings, now: string, createdAt = now, status: Stored["outline_status"] = "planned"): Stored { return { project_id: id, project_type: "long_story_project", title: s.title, logline: s.logline, overview: s.overview, genre: s.genre, tone: s.tone, theme: s.theme, episode_count: s.episodeCount, episode_duration_seconds: s.episodeDurationSeconds, platform: s.platform, aspect_ratio: s.aspectRatio, audience: s.audience, notes: s.notes, starting_state: s.startingState, midpoint: s.midpoint, ending_direction: s.endingDirection, story_flow_summary: s.storyFlowSummary, created_at: createdAt, updated_at: now, outline_status: status }; }
function summary(s: Stored): LongProjectSummary { return { id: s.project_id, title: s.title, logline: s.logline, episodeCount: s.episode_count, outlineStatus: s.outline_status, createdAt: s.created_at, updatedAt: s.updated_at }; }

@Injectable()
export class LongProjectsService {
  constructor(private readonly projectsRoot: string) {}
  private root(id: string): string { if (!isSafeProjectId(id)) throw longUnsafeId(); return path.join(resolveSafeProjectDirectory(this.projectsRoot, id), "long_story"); }
  private files(id: string) { const root = this.root(id); return { root, project: path.join(root, "project.json"), bible: path.join(root, "story_bible.json"), outlines: path.join(root, "episode_outlines.json") }; }
  private async readJson(file: string): Promise<unknown> { try { return JSON.parse(await fs.readFile(file, "utf8")); } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") throw longNotFound(); if (error instanceof SyntaxError) throw longMalformed(); throw longStorageError(); } }
  private parseStored(value: unknown): Stored { const d = object(value); const known = new Set(["project_id", "project_type", "title", "logline", "overview", "genre", "tone", "theme", "episode_count", "episode_duration_seconds", "platform", "aspect_ratio", "audience", "notes", "starting_state", "midpoint", "ending_direction", "story_flow_summary", "created_at", "updated_at", "outline_status", "outline_prompt_request"]); if (Object.keys(d).some((key) => !known.has(key))) throw longInvalidData(); try { const result = setStored(text(d.project_id, true), settings({ title: d.title, logline: d.logline, overview: d.overview, genre: d.genre, tone: d.tone, theme: d.theme, episodeCount: d.episode_count, episodeDurationSeconds: d.episode_duration_seconds, platform: d.platform, aspectRatio: d.aspect_ratio, audience: d.audience, notes: d.notes, startingState: d.starting_state, midpoint: d.midpoint, endingDirection: d.ending_direction, storyFlowSummary: d.story_flow_summary }), text(d.updated_at, true), text(d.created_at, true), d.outline_status === "outline_ready" ? "outline_ready" : d.outline_status === "planned" ? "planned" : (() => { throw longInvalidData(); })()); if (d.project_type !== "long_story_project") throw longInvalidData(); if (d.outline_prompt_request !== undefined) result.outline_prompt_request = d.outline_prompt_request as Stored["outline_prompt_request"]; return result; } catch (error) { if (error instanceof Error && "getStatus" in error) throw error; throw longInvalidData(); } }
  private async load(id: string): Promise<Stored> { const stored = this.parseStored(await this.readJson(this.files(id).project)); if (stored.project_id !== id) throw longInvalidData(); return stored; }
  private async outlines(id: string, count: number): Promise<LongEpisodeOutline[]> { const raw = await this.readJson(this.files(id).outlines); if (!Array.isArray(raw) || raw.length !== count) throw longInvalidData(); return raw.map((item, index) => { const d = object(item); if (d.episode_number !== index + 1 || typeof d.title !== "string" || typeof d.summary !== "string" || typeof d.main_event !== "string" || typeof d.conflict !== "string" || typeof d.cliffhanger !== "string" || typeof d.next_episode_hook !== "string" || (d.status !== "planned" && d.status !== "outline_ready")) throw longInvalidData(); return { episodeNumber: index + 1, title: d.title, summary: d.summary, mainEvent: d.main_event, conflict: d.conflict, cliffhanger: d.cliffhanger, nextEpisodeHook: d.next_episode_hook, status: d.status }; }); }
  private async project(id: string): Promise<LongProject> { const s = await this.load(id); const bible = object(await this.readJson(this.files(id).bible)); const basic = object(bible.basic); const world = object(bible.world); return { ...summary(s), settings: toSettings(s), storyBible: { basic, world }, episodes: await this.outlines(id, s.episode_count) }; }
  async create(request: CreateLongProjectRequest): Promise<CreateLongProjectResponse> { const id = text(request?.projectId, true); if (!isSafeProjectId(id)) throw longUnsafeId(); const input = settings(request?.settings); const now = new Date().toISOString(); const stored = setStored(id, input, now); const files = this.files(id); try { await fs.mkdir(files.root, { recursive: false }); } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") { try { await fs.mkdir(path.dirname(files.root), { recursive: true }); await fs.mkdir(files.root); } catch (nested) { if ((nested as NodeJS.ErrnoException).code === "EEXIST") throw longExists(); throw longStorageError(); } } else if ((error as NodeJS.ErrnoException).code === "EEXIST") throw longExists(); else throw longStorageError(); } try { await Promise.all([atomicWriteUtf8File(files.project, JSON.stringify(stored, null, 2)), atomicWriteUtf8File(files.bible, JSON.stringify({ basic: { title: input.title, logline: input.logline, overview: input.overview, genre: input.genre, tone: input.tone, theme: input.theme, ending_direction: input.endingDirection, audience: input.audience }, world: {}, characters: [], locations: [], props: [], secrets: [], foreshadowing: [], summaries: {}, updated_at: now }, null, 2)), atomicWriteUtf8File(files.outlines, JSON.stringify(Array.from({ length: input.episodeCount }, (_, i) => ({ episode_number: i + 1, title: `Episode ${i + 1}`, summary: "", main_event: "", conflict: "", cliffhanger: "", next_episode_hook: "", status: "planned" })), null, 2))]); } catch { throw longStorageError(); } return { project: await this.project(id) }; }
  async list(): Promise<ListLongProjectsResponse> { let entries: string[]; try { entries = (await fs.readdir(this.projectsRoot, { withFileTypes: true })).filter((x) => x.isDirectory() && isSafeProjectId(x.name)).map((x) => x.name); } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return { projects: [] }; throw longStorageError(); } const projects: LongProjectSummary[] = []; for (const id of entries) { try { projects.push(summary(await this.load(id))); } catch { /* Python catalog skips unreadable entries. */ } } return { projects: projects.sort((a, b) => Date.parse(b.updatedAt) - Date.parse(a.updatedAt)) }; }
  async get(id: string): Promise<GetLongProjectResponse> { return { project: await this.project(id.trim()) }; }
  async getSettings(id: string): Promise<GetLongProjectSettingsResponse> { return { settings: toSettings(await this.load(id.trim())) }; }
  async updateSettings(id: string, request: UpdateLongProjectSettingsRequest): Promise<UpdateLongProjectSettingsResponse> { const prior = await this.load(id.trim()); const updated = setStored(prior.project_id, settings(request?.settings), new Date().toISOString(), prior.created_at, prior.outline_status); updated.outline_prompt_request = prior.outline_prompt_request; try { await atomicWriteUtf8File(this.files(prior.project_id).project, JSON.stringify(updated, null, 2)); } catch { throw longStorageError(); } return { project: await this.project(prior.project_id) }; }
  private prompt(s: Stored): string { return ["[Long project outline]", `Title: ${s.title}`, `Logline: ${s.logline}`, `Overview: ${s.overview || "unspecified"}`, `Genre: ${s.genre || "unspecified"}`, `Tone: ${s.tone || "unspecified"}`, `Episodes: ${s.episode_count}`, `Duration seconds: ${s.episode_duration_seconds}`, "Generate only project overview and episode outlines. Do not generate scripts, images, or videos."].join("\n"); }
  async preview(id: string): Promise<CreateLongProjectOutlinePreviewResponse> { const s = await this.load(id.trim()); const prompt = this.prompt(s); return { preview: { projectId: s.project_id, prompt, promptSha256: crypto.createHash("sha256").update(prompt, "utf8").digest("hex"), episodeCount: s.episode_count } }; }
  async approve(id: string, request: ApproveLongProjectOutlineRequest): Promise<ApproveLongProjectOutlineResponse> { const s = await this.load(id.trim()); if (s.outline_status !== "planned") throw longOutlineNotAllowed(); const preview = await this.preview(s.project_id); if (!(request && request.approved === true && typeof request.prompt === "string" && request.prompt.trim() && request.promptSha256 === preview.preview.promptSha256)) throw longOutlineStale(); const modified = request.prompt !== preview.preview.prompt; const now = new Date().toISOString(); const fields = ["overview", "genre", "tone", "theme", "starting_state", "midpoint", "ending_direction", "story_flow_summary"] as const; for (const field of fields) if (!s[field]) s[field] = `${s.title} ${field.replaceAll("_", " ")}`; s.outline_status = "outline_ready"; s.updated_at = now; s.outline_prompt_request = { prompt_sha256: crypto.createHash("sha256").update(request.prompt, "utf8").digest("hex"), prompt: request.prompt, approved_at: now, modified }; const generated = Array.from({ length: s.episode_count }, (_, i) => ({ episode_number: i + 1, title: `Episode ${i + 1}: ${s.title}`, summary: `${s.logline} — episode ${i + 1}`, main_event: `Episode ${i + 1} main event`, conflict: "Unresolved conflict", cliffhanger: i + 1 === s.episode_count ? "Story conclusion approaches" : `Continue to episode ${i + 2}`, next_episode_hook: i + 1 === s.episode_count ? "" : `Episode ${i + 2}`, status: "outline_ready" })); try { await atomicWriteUtf8File(this.files(s.project_id).project, JSON.stringify(s, null, 2)); await atomicWriteUtf8File(this.files(s.project_id).outlines, JSON.stringify(generated, null, 2)); } catch { throw longStorageError(); } return { project: await this.project(s.project_id), approvedAt: now, promptSha256: s.outline_prompt_request.prompt_sha256, modified }; }
}
